# Домашнее задание #1

Для начала вам понадобится импортировать модуль `numpy` как `np`

In [1]:
import numpy as np

## Задача №1

Считайте (через `input`) 2 числа: <br>
`n` - размер `Numpy` вектора; <br>
`x` - координата элемента вектора, который должен быть равен `1`. Остальные должны быть равны `0`. <br>
Создайте вектор размера `n`, в котором все элементы равны `0`, кроме элемента с номером `x` - он равен `1`.


In [15]:
print ("Введите размер вектора и номер элемента через пробел")
n, x = map(int, input().split())

if x>4: #проверка, если x>n
    print ("*! Номер элемента превышает размер вектора, введите снова !*")
    n, x = map(int, input().split())

vec = np.zeros(n)
vec[x] = 1

print (vec)

Введите размер вектора и номер элемента через пробел
5 4
[0. 0. 0. 0. 1.]


## Задача №2

Считайте 3 числа: `n, m, s`. Создайте `Numpy` вектор, состоящий из чисел от `n` до `m` с шагом `s`.

In [24]:
n = 1
m = 6
s = 2
vec = np.arange(n, m, s)
print (vec)

[1 3 5]


## Задача №3

Создайте матрицу `3х3` со значениями от `0` до `8`. Значения нужно сгенерировать.

In [67]:
print (np.random.randint(0, 9, (3,3)))

[[8 3 0]
 [0 0 8]
 [0 6 6]]


## Задача №4

1. Создайте матрицу `4х4` со случайными значениями.
2. Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой.

In [66]:
myMatrix = np.random.randint(0, 10, size=(4,4))
print (myMatrix)

print (f'Макс. знач. = {np.max(myMatrix[0, :])}')
print (f'Мин. знач. = {np.min(myMatrix[1, :])}')
print (f'Среднее знач. = {np.mean(myMatrix[2, :])}')
print (f'Сумма = {np.sum(myMatrix[3, :])}')

[[0 0 6 4]
 [3 3 2 9]
 [2 3 7 0]
 [9 1 7 2]]
Макс. знач. = 6
Мин. знач. = 2
Среднее знач. = 3.0
Сумма = 19


## Задача №5

Создайте диагональную матрицу `5х5`, все ненулевые элементы равны 5.

In [60]:
print (np.eye(5,5)*5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


## Задача №6

Создайте `Numpy` массив случайных чисел размерности `6х6х6` и найдите максимальное значение среди всех элементов.

In [65]:
myMatrix = np.random.randint(0, 10, size=(6,6,6))
print (f'Максимальное число матрицы = {np.max(myMatrix)}')

Максимальное число матрицы = 9


## Задача №7

Напишите функцию, которая принимает на вход 2 `Numpy` матрицы, проверяет, можно ли их перемножить, и если можно - то перемножает и возвращает транспонированную результирующую матрицу.

In [73]:
#Можно перемножить
A = np.array ([[1, 2], [3, 4], [5, 6]])
B = np.array ([[0, 1], [0, 2]])

if A.shape[1] == B.shape[0]:
    C = np.transpose (A @ B)
    print (C)
else: print ("Нельзя перемножить")

#Нельзя перемножить
A = np.array ([[1, 2], [3, 4], [5, 6]])
B = np.array ([[0, 1], [0, 2], [0, 3]])

if A.shape[1] == B.shape[0]:
    C = np.transpose (A @ B)
    print (C)
else: print ("Нельзя перемножить")

[[ 0  0  0]
 [ 5 11 17]]
Нельзя перемножить


## Задача №8

Дана функция:

$$ f(x_1, x_2) = x_1^2 + 2x_2^2 + e^{x_1+x_2} $$

Найдите минимум данной функции, завершив вычисления при погрешности $$\varepsilon = 0.5 $$, выбрав в качестве начального приблежения точку `(0, 0)` и коэффициент шага $$ H=0.1. $$

In [74]:
def func(x, y):
    return x*x + 2.0 * y*y + np.exp(x + y)

def f_x(func, x, y, eps=0.001):
    return (func(x+eps, y) - func(x, y)) / eps

def f_y(func, x, y, eps=0.001):
    return (func(x, y+eps) - func(x, y)) / eps

EPS = 0.001
INIT = np.array([1.0, -1.75])
LEARN_RATE = 0.05
ITER = 10000

X_prev = INIT
delta = 1
for i in range(ITER):
    if delta > EPS:
        fxx = f_x(func, X_prev[0], X_prev[1], eps=0.001)
        fyy = f_y(func, X_prev[0], X_prev[1], eps=0.001)
        grad = np.array([fxx, fyy])

        X_next = X_prev - LEARN_RATE * grad    

        delta = np.sqrt(np.sum(grad*grad))
        
        X_prev = X_next
        
    else:
        break
        
print(f"Значение функции {func(X_next[0], X_next[1]).round(4)}")
print(f"x_min {X_next[0].round(4)}")
print(f"y_min {X_next[1].round(4)}")
print(f"Производная в x_min {f_x(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Производная в y_min {f_y(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Градиент {np.sqrt((grad**2).sum()).round(9)}")

Значение функции 0.7723
x_min -0.3128
y_min -0.1569
Производная в x_min 0.0008
Производная в y_min -0.0002
Градиент 0.000963264
